[package]
name = "xmpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jid = "0.9.4"
minidom = "0.15.2"
xmpp-parsers = "0.19.2"
